### ISSUE TITLE
いいところ診断の結果に優しさを追加したい

### ISSUE THREAD

**Issue by y162** [y162/assessment#1]
以下の結果を追加したい

'{userName}のいいところは優しさです。あなたの優しい雰囲気や立ち振る舞いに多くの人が癒やされています。'

**Comment by y162** [comment]
これから対応したいと思います。

**Comment by y621** [comment]
b5b0548471285f377286f1e525b30f30f0bd01a5で対応しました。

**Comment by y162** [comment]
b5b0548471285f377286f1e525b30f30f0bd01a5　で対応しました。
